name: Call Shared Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-sandbox:
    uses: deljdlx/github-tools/.github/workflows/deploy.yml@main
    with:
      host_name: "match3.jlb.ninja"
      repo_name: "dc-match3"
      repo_owner: "deljdlx"
      deploy_folder: "/home/jdlxt/stack"
    secrets:
      ssh_key: ${{ secrets.DEPLOY_KEY }}
